/* The following code was generated by JFlex 1.3.5 on 6/28/18 3:58 AM */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 6/28/18 3:58 AM from the specification file
 * <tt>file:/C:/Users/Daniel/Desktop/com_fortran/compiler/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int STRING = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\11\1\11\2\0\1\11\22\0\1\30\1\42\1\7\2\0"+
    "\1\10\2\0\1\16\1\17\1\14\1\13\1\12\1\3\2\0\1\4"+
    "\11\6\1\45\1\0\1\44\1\41\1\43\2\0\3\1\2\5\25\1"+
    "\4\0\1\2\1\0\1\33\1\1\1\22\1\27\1\26\1\20\1\37"+
    "\1\36\1\24\2\1\1\34\1\40\1\15\1\25\1\31\1\1\1\32"+
    "\1\35\1\23\1\21\1\1\1\46\3\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    39,    78,   117,   156,   195,   234,   273,    78,   156, 
       78,   117,    78,    78,   312,   351,   390,   429,   468,   507, 
      546,   585,   624,   663,   702,   741,   780,   819,   858,   234, 
       78,   897,   936,   975,  1014,  1053,   117,  1092,  1131,  1170, 
      117,  1209,  1248,    78,    78,    78,    78,    78,  1287,  1326, 
     1365,   234,  1404,  1443,  1482,  1521,  1560,  1599,  1638,  1677, 
     1716,  1755,  1794,  1833,  1872,   117,  1911,  1950,  1989,  2028, 
     2067,  2106,   117,  2145,  2184,  2223,  2262,  2301,  2340,  2379, 
     2418,  2457,  2496,   117,  2535,   117,  2574,  2613,  2652,  2691, 
     2730,    78,    78,  2769,  2808,  2847,  2886,  2925,   117,  2964, 
     3003,  3042,    78,   117,   117,  3081,  3120,  3159,  3198,   117, 
     3237,  3276,  3315,  3354,  3393,  3432,  3471,  3510,    78,  3549, 
       78,    78
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\3\1\5\1\6\1\4\1\6\1\7"+
    "\1\3\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\4\1\20\1\21\1\22\1\4\1\23\1\24"+
    "\1\10\1\25\1\26\6\4\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\47\3\50\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\10\4\1\0\10\4\5\0\1\4\4\0"+
    "\1\6\1\0\1\6\44\0\1\6\1\35\1\6\17\0"+
    "\2\35\17\0\7\36\1\37\1\40\36\36\11\0\1\10"+
    "\16\0\1\10\17\0\2\4\1\0\3\4\6\0\1\4"+
    "\2\0\1\4\1\41\6\4\1\0\10\4\5\0\1\4"+
    "\1\0\2\4\1\0\3\4\6\0\1\4\2\0\10\4"+
    "\1\0\5\4\1\42\2\4\5\0\1\4\1\0\2\4"+
    "\1\0\3\4\6\0\1\4\2\0\10\4\1\0\5\4"+
    "\1\43\2\4\5\0\1\4\1\0\2\4\1\0\3\4"+
    "\6\0\1\44\2\0\1\45\7\4\1\0\7\4\1\46"+
    "\5\0\1\4\1\0\2\4\1\0\3\4\6\0\1\47"+
    "\2\0\10\4\1\0\3\4\1\50\4\4\5\0\1\4"+
    "\1\0\2\4\1\0\3\4\6\0\1\4\2\0\5\4"+
    "\1\51\2\4\1\0\10\4\5\0\1\4\1\0\2\4"+
    "\1\0\3\4\6\0\1\4\2\0\10\4\1\0\1\4"+
    "\1\52\6\4\5\0\1\4\1\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\6\4\1\53\1\4\1\0\10\4"+
    "\5\0\1\4\41\0\1\54\46\0\1\55\46\0\1\56"+
    "\46\0\1\57\52\0\1\60\2\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\10\4\1\0\5\4\1\61\2\4"+
    "\5\0\1\4\3\0\1\62\2\0\1\63\4\0\1\62"+
    "\33\0\7\36\1\64\1\40\36\36\1\0\2\4\1\0"+
    "\3\4\6\0\1\65\2\0\10\4\1\0\10\4\5\0"+
    "\1\4\1\0\2\4\1\0\3\4\6\0\1\4\2\0"+
    "\10\4\1\0\2\4\1\66\5\4\5\0\1\4\1\0"+
    "\2\4\1\0\3\4\6\0\1\4\2\0\6\4\1\67"+
    "\1\4\1\0\10\4\5\0\1\4\1\0\2\4\1\0"+
    "\3\4\6\0\1\4\2\0\3\4\1\70\4\4\1\0"+
    "\10\4\5\0\1\4\1\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\10\4\1\0\1\71\7\4\5\0\1\4"+
    "\1\0\2\4\1\0\3\4\6\0\1\4\2\0\7\4"+
    "\1\72\1\0\10\4\5\0\1\4\1\0\2\4\1\0"+
    "\3\4\6\0\1\4\2\0\10\4\1\0\4\4\1\73"+
    "\3\4\5\0\1\4\1\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\4\4\1\74\1\75\2\4\1\0\10\4"+
    "\5\0\1\4\1\0\2\4\1\0\3\4\6\0\1\4"+
    "\2\0\10\4\1\0\2\4\1\76\5\4\5\0\1\4"+
    "\1\0\2\4\1\0\3\4\6\0\1\4\2\0\4\4"+
    "\1\77\3\4\1\0\10\4\5\0\1\4\6\0\1\63"+
    "\44\0\1\63\1\0\1\63\41\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\2\4\1\100\5\4\1\0\10\4"+
    "\5\0\1\4\1\0\2\4\1\0\3\4\6\0\1\4"+
    "\2\0\10\4\1\0\1\4\1\101\6\4\5\0\1\4"+
    "\1\0\2\4\1\0\3\4\6\0\1\102\2\0\10\4"+
    "\1\0\10\4\5\0\1\4\1\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\6\4\1\103\1\4\1\0\10\4"+
    "\5\0\1\4\1\0\2\4\1\0\3\4\6\0\1\4"+
    "\2\0\10\4\1\0\3\4\1\104\4\4\5\0\1\4"+
    "\1\0\2\4\1\0\3\4\6\0\1\4\2\0\10\4"+
    "\1\105\10\4\5\0\1\4\1\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\6\4\1\106\1\4\1\0\10\4"+
    "\5\0\1\4\1\0\2\4\1\0\3\4\6\0\1\107"+
    "\2\0\10\4\1\0\10\4\5\0\1\4\1\0\2\4"+
    "\1\0\3\4\6\0\1\4\2\0\10\4\1\0\6\4"+
    "\1\110\1\4\5\0\1\4\1\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\7\4\1\111\1\0\10\4\5\0"+
    "\1\4\1\0\2\4\1\0\3\4\6\0\1\4\2\0"+
    "\10\4\1\0\3\4\1\112\4\4\5\0\1\4\1\0"+
    "\2\4\1\0\3\4\6\0\1\4\2\0\3\4\1\113"+
    "\4\4\1\0\10\4\5\0\1\4\1\0\2\4\1\0"+
    "\3\4\6\0\1\4\2\0\10\4\1\0\2\4\1\114"+
    "\5\4\5\0\1\4\1\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\10\4\1\0\6\4\1\115\1\4\5\0"+
    "\1\4\1\0\2\4\1\0\3\4\6\0\1\4\2\0"+
    "\4\4\1\116\3\4\1\0\10\4\5\0\1\4\20\0"+
    "\1\117\3\0\1\120\2\0\1\121\1\0\1\122\16\0"+
    "\2\4\1\0\3\4\6\0\1\4\2\0\10\4\1\123"+
    "\10\4\5\0\1\4\1\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\3\4\1\124\4\4\1\0\10\4\5\0"+
    "\1\4\1\0\2\4\1\0\3\4\6\0\1\4\2\0"+
    "\10\4\1\0\1\4\1\125\6\4\5\0\1\4\1\0"+
    "\2\4\1\0\3\4\6\0\1\4\2\0\6\4\1\126"+
    "\1\4\1\0\10\4\5\0\1\4\1\0\2\4\1\0"+
    "\3\4\6\0\1\4\2\0\4\4\1\127\3\4\1\0"+
    "\10\4\5\0\1\4\1\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\2\4\1\130\5\4\1\0\10\4\5\0"+
    "\1\4\1\0\2\4\1\0\3\4\6\0\1\4\2\0"+
    "\6\4\1\131\1\4\1\0\10\4\5\0\1\4\1\0"+
    "\2\4\1\0\3\4\6\0\1\4\2\0\2\4\1\132"+
    "\5\4\1\0\10\4\5\0\1\4\21\0\1\133\45\0"+
    "\1\134\53\0\1\135\53\0\1\136\40\0\1\137\23\0"+
    "\2\4\1\0\3\4\6\0\1\4\2\0\10\4\1\0"+
    "\2\4\1\140\5\4\5\0\1\4\1\0\2\4\1\0"+
    "\3\4\6\0\1\4\2\0\5\4\1\141\2\4\1\0"+
    "\10\4\5\0\1\4\1\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\3\4\1\142\4\4\1\0\10\4\5\0"+
    "\1\4\1\0\2\4\1\0\3\4\6\0\1\4\2\0"+
    "\10\4\1\0\1\4\1\143\6\4\5\0\1\4\1\0"+
    "\2\4\1\0\3\4\6\0\1\4\2\0\4\4\1\144"+
    "\3\4\1\0\10\4\5\0\1\4\15\0\1\145\56\0"+
    "\1\146\41\0\1\147\27\0\2\4\1\0\3\4\6\0"+
    "\1\4\2\0\10\4\1\0\7\4\1\150\5\0\1\4"+
    "\1\0\2\4\1\0\3\4\6\0\1\151\2\0\10\4"+
    "\1\0\10\4\5\0\1\4\1\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\6\4\1\152\1\4\1\0\10\4"+
    "\5\0\1\4\1\0\2\4\1\0\3\4\6\0\1\4"+
    "\2\0\3\4\1\153\4\4\1\0\10\4\5\0\1\4"+
    "\22\0\1\154\63\0\1\155\10\0\2\4\1\0\3\4"+
    "\6\0\1\4\2\0\10\4\1\0\1\4\1\156\6\4"+
    "\5\0\1\4\1\0\2\4\1\0\3\4\6\0\1\4"+
    "\2\0\10\4\1\157\10\4\5\0\1\4\23\0\1\160"+
    "\55\0\1\161\31\0\1\162\55\0\1\163\55\0\1\164"+
    "\40\0\1\165\46\0\1\166\61\0\1\167\23\0\1\170"+
    "\46\0\1\171\57\0\1\172\20\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  1,  1,  1,  1,  9,  1,  9,  1,  9,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  9,  0, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9, 
     1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0, 
     0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  0,  9,  9,  0,  0,  1, 
     1,  1,  1,  1,  0,  0,  9,  1,  1,  1,  1,  0,  0,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  9,  0,  9,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */


    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }

    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code,
						new Location(yyline+1, yycolumn +1, yychar),
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }

    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }

    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" +
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3588];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 114) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 40: 
          {  return symbolFactory.newSymbol("DO",DO);  }
        case 123: break;
        case 36: 
          {  return symbolFactory.newSymbol("IF", IF);  }
        case 124: break;
        case 24: 
          {  return symbolFactory.newSymbol("GT",GT);  }
        case 125: break;
        case 22: 
          {  return symbolFactory.newSymbol("EQ",EQ);  }
        case 126: break;
        case 8: 
          {  return symbolFactory.newSymbol("CO", CO);  }
        case 127: break;
        case 5: 
        case 50: 
          {  return symbolFactory.newSymbol("INTEGER_LIT", INTEGER_LIT, Integer.parseInt(yytext()));  }
        case 128: break;
        case 2: 
        case 6: 
        case 23: 
        case 25: 
        case 26: 
          {  throw new Error("Parsing Failed! Illegal character ["+ yytext()+"] at line " + yyline + ", col " + yycolumn);  }
        case 129: break;
        case 103: 
          {  return symbolFactory.newSymbol("PROGRAM", PROGRAM);  }
        case 130: break;
        case 121: 
          {  return symbolFactory.newSymbol("IMPLI", IMPLI);  }
        case 131: break;
        case 4: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 132: break;
        case 10: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 133: break;
        case 44: 
          {  return symbolFactory.newSymbol("NOTEQ",NOTEQ);  }
        case 134: break;
        case 83: 
          {  return symbolFactory.newSymbol("PRINT", PRINT);  }
        case 135: break;
        case 85: 
          {  return symbolFactory.newSymbol("WHILE",WHILE);  }
        case 136: break;
        case 91: 
          {  return symbolFactory.newSymbol("ENDIF ",ENDIF);  }
        case 137: break;
        case 92: 
          {  return symbolFactory.newSymbol("ENDDO",ENDDO);  }
        case 138: break;
        case 3: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 27: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
        case 37: 
        case 38: 
        case 39: 
        case 41: 
        case 42: 
        case 48: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 66: 
        case 67: 
        case 70: 
        case 71: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 84: 
        case 86: 
        case 87: 
        case 88: 
        case 89: 
        case 95: 
        case 96: 
        case 97: 
        case 99: 
        case 105: 
        case 106: 
          {  return symbolFactory.newSymbol("IDENT",IDENT, yytext());  }
        case 139: break;
        case 118: 
          {  return symbolFactory.newSymbol("ENDPROGRAM", ENDPROGRAM);  }
        case 140: break;
        case 43: 
          {  return symbolFactory.newSymbol("EQ2",EQ2);  }
        case 141: break;
        case 98: 
          {  return symbolFactory.newSymbol("INT",INT);  }
        case 142: break;
        case 104: 
          {  return symbolFactory.newSymbol("FUNCTION", FUNCTION);  }
        case 143: break;
        case 120: 
          {  return symbolFactory.newSymbol("ENDFUNCTION", ENDFUNCTION);  }
        case 144: break;
        case 9: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 145: break;
        case 45: 
          {  return symbolFactory.newSymbol("GTEQ",GTEQ);  }
        case 146: break;
        case 46: 
          {  return symbolFactory.newSymbol("LTEQ",LTEQ);  }
        case 147: break;
        case 65: 
          {  return symbolFactory.newSymbol("THEN", THEN);  }
        case 148: break;
        case 69: 
          {  return symbolFactory.newSymbol("ELSE", ELSE);  }
        case 149: break;
        case 72: 
          {  return symbolFactory.newSymbol("READ", READ);  }
        case 150: break;
        case 109: 
          {  return symbolFactory.newSymbol("CHARACTER",CHARACTER);  }
        case 151: break;
        case 30: 
        case 51: 
          {  return symbolFactory.newSymbol("STRING_LIT", STRING_LIT, yytext());  }
        case 152: break;
        case 13: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 153: break;
        case 12: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 154: break;
        case 11: 
          {  return symbolFactory.newSymbol("UMINUS", UMINUS);  }
        case 155: break;
        case 47: 
          {  return symbolFactory.newSymbol("TPOINT", TPOINT);  }
        case 156: break;
        case 102: 
          {  return symbolFactory.newSymbol("ELSEIF ",ELSEIF);  }
        case 157: break;
        case 7: 
          {  }
        case 158: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
