
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GTEQ = 25;
  public static final int EQ2 = 30;
  public static final int FUNCTION = 21;
  public static final int INTEGER_LIT = 35;
  public static final int LTEQ = 24;
  public static final int TPOINT = 13;
  public static final int UMINUS = 5;
  public static final int LPAREN = 7;
  public static final int INT = 19;
  public static final int ENDDO = 26;
  public static final int MINUS = 4;
  public static final int CHARACTER = 20;
  public static final int RPAREN = 8;
  public static final int CO = 2;
  public static final int ELSEIF = 28;
  public static final int LT = 34;
  public static final int ENDFUNCTION = 32;
  public static final int ENDPROGRAM = 31;
  public static final int PLUS = 3;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAM = 18;
  public static final int IDENT = 36;
  public static final int EQ = 22;
  public static final int TIMES = 6;
  public static final int ENDIF = 27;
  public static final int ELSE = 10;
  public static final int READ = 15;
  public static final int WHILE = 11;
  public static final int IMPLI = 29;
  public static final int THEN = 17;
  public static final int END = 14;
  public static final int STRING_LIT = 37;
  public static final int GT = 33;
  public static final int PRINT = 16;
  public static final int DO = 12;
  public static final int NOTEQ = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CO",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "TPOINT",
  "END",
  "READ",
  "PRINT",
  "THEN",
  "PROGRAM",
  "INT",
  "CHARACTER",
  "FUNCTION",
  "EQ",
  "NOTEQ",
  "LTEQ",
  "GTEQ",
  "ENDDO",
  "ENDIF",
  "ELSEIF",
  "IMPLI",
  "EQ2",
  "ENDPROGRAM",
  "ENDFUNCTION",
  "GT",
  "LT",
  "INTEGER_LIT",
  "IDENT",
  "STRING_LIT"
  };
}

